#!/usr/bin/env node
/**
 * Bootstrap script — run once with `node bootstrap.mjs` from the go-tools-mcp directory.
 * Creates src/data/ and scripts/ directories only.
 * Delete this file after running.
 */
import { mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const root = dirname(fileURLToPath(import.meta.url));

// ── 1. Create directories ────────────────────────────────────────────────────
mkdirSync(join(root, "src", "data"), { recursive: true });
mkdirSync(join(root, "scripts"), { recursive: true });
console.log("✓ Directories created");

console.log("Done. You can now delete bootstrap.mjs.");
// (writeFileSync calls removed — source files are written by the Copilot agent using the create tool)
// writeFileSync(
  join(root, "src", "data", "index.ts"),
  `// AUTO-GENERATED by scripts/update-index.mjs — do not edit manually.
// Run \`npm run update-index\` (or \`npm install\`) to regenerate from ../go-tools-index.md.
export const INDEX_CONTENT = "";
`
);
console.log("✓ src/data/index.ts");

// ── 3. src/parser.ts ────────────────────────────────────────────────────────
writeFileSync(
  join(root, "src", "parser.ts"),
  `export interface ModuleInfo {
  /** e.g. "go-relay/v2" */
  name: string;
  /** e.g. "github.com/mirkobrombin/go-relay/v2" */
  importPath: string;
  /** First descriptive sentence from the module section */
  description: string;
  /** Full Markdown content of the section */
  content: string;
}

export interface ParsedIndex {
  modules: ModuleInfo[];
  /** "## Design principles" + "## Ecosystem integration pattern" sections */
  ecosystem: string;
}

/**
 * Parses the go-tools-index.md content into structured data.
 * Sections are delimited by \`\\n---\\n\` horizontal rules.
 */
export function parseIndex(markdown: string): ParsedIndex {
  const parts = markdown.split(/\\n---\\n/);

  const modules: ModuleInfo[] = [];
  const ecosystemParts: string[] = [];

  for (const part of parts) {
    const trimmed = part.trim();
    if (!trimmed) continue;

    if (/^### go-/.test(trimmed)) {
      const mod = parseModuleSection(trimmed);
      if (mod) modules.push(mod);
    } else if (
      trimmed.includes("## Design principles") ||
      trimmed.includes("## Ecosystem integration pattern") ||
      trimmed.includes("## Module quick-reference")
    ) {
      ecosystemParts.push(trimmed);
    }
  }

  return { modules, ecosystem: ecosystemParts.join("\\n\\n---\\n\\n") };
}

function parseModuleSection(section: string): ModuleInfo | null {
  const lines = section.split("\\n");

  // Header: "### go-relay/v2"
  const headerMatch = lines[0]?.match(/^### (.+)$/);
  if (!headerMatch) return null;
  const name = headerMatch[1].trim();

  // Import path: backtick line like \`github.com/mirkobrombin/go-relay/v2\`
  const importLine = lines.find((l) => /^\`github\\.com\\//.test(l));
  const importPath = importLine ? importLine.replace(/\`/g, "").trim() : "";

  // Description: first non-empty line that is not a header, code fence, or table
  let pastImport = false;
  let description = "";
  for (const line of lines.slice(1)) {
    if (!pastImport) {
      if (line.startsWith("\`") && line.includes("github.com")) {
        pastImport = true;
      }
      continue;
    }
    const t = line.trim();
    if (!t) continue;
    if (t.startsWith("#") || t.startsWith("\`") || t.startsWith("|") || t.startsWith(">")) continue;
    description = t;
    break;
  }

  return { name, importPath, description, content: section };
}

/**
 * Finds a module by name or partial match.
 * Supports: exact name, suffix without "go-" prefix, suffix without version,
 * and substring match on name or import path.
 */
export function findModule(modules: ModuleInfo[], query: string): ModuleInfo | undefined {
  const q = query.toLowerCase().trim();

  // 1. Exact match
  const exact = modules.find((m) => m.name.toLowerCase() === q);
  if (exact) return exact;

  // 2. Strip "go-" prefix and version suffix for lenient matching
  const stripped = q.replace(/^go-/, "").replace(/\\/v\\d+$/, "");
  const lenient = modules.find((m) => {
    const base = m.name.toLowerCase().replace(/^go-/, "").replace(/\\/v\\d+$/, "");
    return base === stripped;
  });
  if (lenient) return lenient;

  // 3. Substring match on name or import path
  return modules.find(
    (m) => m.name.toLowerCase().includes(q) || m.importPath.toLowerCase().includes(q)
  );
}

export interface SearchResult {
  module: ModuleInfo;
  snippets: string[];
  score: number;
}

/**
 * Full-text search across all module documentation.
 * Returns results sorted by relevance score (descending).
 */
export function searchModules(modules: ModuleInfo[], query: string): SearchResult[] {
  const terms = query
    .toLowerCase()
    .split(/\\s+/)
    .filter((t) => t.length > 1);

  if (terms.length === 0) return [];

  const results: SearchResult[] = [];

  for (const module of modules) {
    const text = module.content.toLowerCase();
    let score = 0;
    const snippets: string[] = [];

    for (const term of terms) {
      let pos = 0;
      let termHits = 0;

      while ((pos = text.indexOf(term, pos)) !== -1) {
        termHits++;
        if (snippets.length < 3) {
          const start = Math.max(0, pos - 50);
          const end = Math.min(module.content.length, pos + 120);
          const raw = module.content.slice(start, end).replace(/\\n+/g, " ").trim();
          if (!snippets.some((s) => s.slice(0, 40) === raw.slice(0, 40))) {
            snippets.push(\`…\${raw}…\`);
          }
        }
        pos += term.length;
      }

      if (module.name.toLowerCase().includes(term)) score += termHits + 10;
      else if (module.description.toLowerCase().includes(term)) score += termHits + 5;
      else score += termHits;
    }

    if (score > 0) results.push({ module, snippets, score });
  }

  return results.sort((a, b) => b.score - a.score);
}
`
);
console.log("✓ src/parser.ts");

// ── 4. src/index.ts ─────────────────────────────────────────────────────────
writeFileSync(
  join(root, "src", "index.ts"),
  `import { McpAgent } from "agents/mcp";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { z } from "zod";
import { INDEX_CONTENT } from "./data/index";
import { parseIndex, findModule, searchModules } from "./parser";

// Parse once at Worker startup — data is static
const { modules, ecosystem } = parseIndex(INDEX_CONTENT);

interface Env {
  GoToolsMCP: DurableObjectNamespace;
}

export class GoToolsMCP extends McpAgent<Env> {
  server = new McpServer({
    name: "go-tools",
    version: "0.1.0",
    description:
      "Reference documentation for the mirkobrombin / Fabricators Go modules ecosystem. " +
      "22 modules covering auth, caching, routing, jobs, ORM, FSM, logging, and more.",
  });

  async init(): Promise<void> {
    // ─── list_modules ──────────────────────────────────────────────────────────
    this.server.tool(
      "list_modules",
      "List all available Go modules with their import paths and one-line descriptions. " +
        "Use this to discover which module handles a specific concern before fetching full docs.",
      {},
      async () => {
        if (modules.length === 0) {
          return {
            content: [
              {
                type: "text" as const,
                text: "Index not loaded. Run \`npm run update-index\` in the go-tools-mcp project and redeploy.",
              },
            ],
          };
        }

        const header = "| Module | Import path | Description |\\n|--------|-------------|-------------|";
        const rows = modules
          .map((m) => \`| **\${m.name}** | \\\`\${m.importPath}\\\` | \${m.description} |\`)
          .join("\\n");

        return { content: [{ type: "text" as const, text: \`\${header}\\n\${rows}\` }] };
      }
    );

    // ─── get_module ────────────────────────────────────────────────────────────
    this.server.tool(
      "get_module",
      "Get complete documentation for a specific Go module — API reference, usage examples, " +
        "configuration options, and integration notes.",
      {
        name: z
          .string()
          .describe(
            "Module name or partial alias. " +
              "Examples: 'go-relay', 'relay', 'go-relay/v2', 'warp', 'state-flow', 'wormhole', 'signal'."
          ),
      },
      async ({ name }) => {
        const mod = findModule(modules, name);

        if (!mod) {
          const available = modules.map((m) => m.name).join(", ");
          return {
            content: [
              {
                type: "text" as const,
                text: \`Module "\${name}" not found.\\n\\nAvailable modules: \${available}\`,
              },
            ],
          };
        }

        return { content: [{ type: "text" as const, text: mod.content }] };
      }
    );

    // ─── search_modules ────────────────────────────────────────────────────────
    this.server.tool(
      "search_modules",
      "Search across all module documentation using keywords or concepts. " +
        "Use this when you are unsure which module handles a specific concern.",
      {
        query: z
          .string()
          .describe(
            "Keywords or concept to search for. " +
              "Examples: 'distributed lock', 'HMAC token signing', 'FSM transitions', " +
              "'retry backoff', 'worker pool', 'saga compensation', 'code-first migration'."
          ),
      },
      async ({ query }) => {
        const results = searchModules(modules, query);

        if (results.length === 0) {
          return {
            content: [
              { type: "text" as const, text: \`No modules found matching "\${query}".\` },
            ],
          };
        }

        const top = results.slice(0, 5);
        const text = top
          .map((r) => {
            const snips = r.snippets
              .slice(0, 2)
              .map((s) => \`  > \${s}\`)
              .join("\\n");
            return \`### \${r.module.name}\\n\\\`\${r.module.importPath}\\\`\\n\${r.module.description}\\n\${snips}\`;
          })
          .join("\\n\\n");

        return { content: [{ type: "text" as const, text }] };
      }
    );

    // ─── get_ecosystem ─────────────────────────────────────────────────────────
    this.server.tool(
      "get_ecosystem",
      "Get the ecosystem integration diagram and design principles — how all modules fit together, " +
        "dependency direction, two-tier async pipeline, caching layer, and data access patterns.",
      {},
      async () => {
        const text = ecosystem.trim() || "Ecosystem section not found in index.";
        return { content: [{ type: "text" as const, text }] };
      }
    );
  }
}

export default {
  fetch: GoToolsMCP.mount("/mcp"),
} satisfies ExportedHandler<Env>;
`
);
console.log("✓ src/index.ts");

// ── 5. scripts/update-index.mjs ─────────────────────────────────────────────
writeFileSync(
  join(root, "scripts", "update-index.mjs"),
  `#!/usr/bin/env node
/**
 * Reads ../go-tools-index.md and generates src/data/index.ts with the content
 * embedded as a TypeScript string constant.
 *
 * Run automatically via \`postinstall\`, or manually with \`npm run update-index\`.
 */
import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const indexPath = join(__dirname, "..", "..", "go-tools-index.md");
const outputPath = join(__dirname, "..", "src", "data", "index.ts");

let content;
try {
  content = readFileSync(indexPath, "utf-8");
} catch (err) {
  console.error(\`[update-index] ERROR: Could not read \${indexPath}\`);
  console.error(\`  Make sure go-tools-index.md exists in the parent directory.\`);
  process.exit(1);
}

// Escape for embedding in a template literal
const escaped = content
  .replace(/\\\\/g, "\\\\\\\\")
  .replace(/\`/g, "\\\\\`")
  .replace(/\\\${/g, "\\\\\${");

const output = \`// AUTO-GENERATED by scripts/update-index.mjs — do not edit manually.
// Run \\\`npm run update-index\\\` (or \\\`npm install\\\`) to regenerate from ../go-tools-index.md.
// Last generated: \${new Date().toISOString()}
export const INDEX_CONTENT = \\\`\${escaped}\\\`;
\`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, output, "utf-8");
console.log(
  \`[update-index] Written src/data/index.ts (\${content.length.toLocaleString()} chars from go-tools-index.md)\`
);
`
);
console.log("✓ scripts/update-index.mjs");

console.log("\n✓ All files written. Delete this bootstrap.mjs when done.");
