// AUTO-GENERATED by update-index.mjs — do not edit manually.
// Run `npm run update-index` (or `npm install`) to regenerate from go-tools-index.md.
// Last generated: 2026-06-04T14:49:26.191Z
export const INDEX_CONTENT = `# go-foundation ecosystem — Go modules reference

All modules are by [Mirko Brombin](https://github.com/mirkobrombin) / [fabricators](https://github.com/fabricatorsltd). Use this as a general reference when instructing agents.

> **Last sync**: June 2026 — reflects go-foundation v1.1.0 + go-wormhole v1.7.x + standalone modules. Supersedes all previous versions.

---

## Migration from go-tools to go-foundation

Many former standalone modules have been merged into \`go-foundation\`. For ~90% of cases, change the import path:

| Old import | New import | Notes |
|---|---|---|
| \`github.com/mirkobrombin/go-auth\` | \`github.com/mirkobrombin/go-foundation/pkg/auth\` | Extended: HMAC, RSA, ECDSA, EdDSA, key rotation |
| \`github.com/mirkobrombin/go-signal/v2\` | \`github.com/mirkobrombin/go-foundation/pkg/events\` | API changed: \`events.Emit[T]\` / \`events.Subscribe[T]\` |
| \`github.com/mirkobrombin/go-relay/v2\` | \`github.com/mirkobrombin/go-foundation/pkg/relay\` | Same API |
| \`github.com/mirkobrombin/go-guard\` | \`github.com/mirkobrombin/go-foundation/pkg/guard\` | Same API |
| \`github.com/mirkobrombin/go-lock\` | \`github.com/mirkobrombin/go-foundation/pkg/lock\` | Now includes InMemoryLocker |
| \`github.com/mirkobrombin/go-metrics\` | \`github.com/mirkobrombin/go-foundation/pkg/metrics\` | Extended: Counter, Gauge, Histogram, Timer |
| \`github.com/mirkobrombin/go-worker\` | \`github.com/mirkobrombin/go-foundation/pkg/worker\` | Same API |
| \`github.com/mirkobrombin/go-secrets\` | \`github.com/mirkobrombin/go-foundation/pkg/secrets\` | Extended: CipherStore, PrefixStore, FallbackStore |
| \`github.com/mirkobrombin/go-retry\` | \`github.com/mirkobrombin/go-foundation/pkg/resiliency\` | Use \`resiliency.Retry\` directly |
| \`github.com/mirkobrombin/go-plugin\` | \`github.com/mirkobrombin/go-foundation/pkg/plugin\` | Same API |
| \`github.com/mirkobrombin/go-revert/v2\` | \`github.com/mirkobrombin/go-foundation/pkg/saga\` | Renamed: \`revert.New()\` → \`saga.New()\`, \`Add\`/\`AddGroup\` same |
| \`github.com/mirkobrombin/go-state-flow\` | \`github.com/mirkobrombin/go-foundation/pkg/fsm\` | Same struct-tag API |
| \`github.com/mirkobrombin/go-struct-flags/v2\` | \`github.com/mirkobrombin/go-foundation/pkg/tags\` | Deprecated. Use \`pkg/tags\` for new code |
| \`github.com/mirkobrombin/go-conf-builder/v2\` | \`github.com/mirkobrommin/go-foundation/pkg/configuration\` | .NET-style multi-source provider pattern |
| \`github.com/mirkobrombin/go-cli-builder/v2\` | \`github.com/mirkobrombin/go-foundation/pkg/app\` | See \`pkg/app\` + \`pkg/hosting\` |
| \`github.com/mirkobrombin/go-logger\` | \`github.com/mirkobrombin/go-foundation/pkg/logger\` | Same sinks + CLEFSink |
| \`github.com/mirkobrombin/go-httpx\` | \`github.com/mirkobrombin/go-foundation/pkg/httpx\` | Same API |
| \`github.com/mirkobrombin/go-module-router/v2\` | \`github.com/mirkobrombin/go-foundation/pkg/srv\` + \`pkg/bind\` + \`pkg/dispatcher\` | Deprecated in v1.1.0. HTTP: \`pkg/srv\`, Actions: \`pkg/dispatcher\` |

---

## Modules

---

### go-foundation

\`github.com/mirkobrombin/go-foundation\`

The standard library's missing standard library. Zero external dependencies. Every other module in the ecosystem depends on this. All packages live under \`pkg/\`.

#### \`pkg/hosting\` — Application host

Manages application lifecycle: sequential \`Start\` / reverse \`Stop\`, startup timeout, health endpoints, \`HostState\` atomic tracking.

\`\`\`go
h := hosting.NewBuilder().
    WithAddr(":8080").
    AddService(myBackgroundSvc).           // BackgroundService (Execute only)
    AddHostedService(myHostedSvc).          // HostedService (Start + Stop)
    AddHostedService(&hosting.BackgroundServiceAdapter{Svc: myBgSvc}).
    Build()

h.Run(ctx)   // blocks until SIGINT/SIGTERM
\`\`\`

- \`BackgroundService\` — long-running, started in parallel, \`Execute(ctx) error\`
- \`HostedService\` — managed lifecycle, \`Start(ctx) error\` + \`Stop(ctx) error\`
- \`BackgroundServiceAdapter\` — wraps \`BackgroundService\` as \`HostedService\`
- Health: \`/health/live\`, \`/health/ready\` via \`pkg/health\`
- \`HostState\`: Starting → Running → Stopping → Stopped (atomic)

#### \`pkg/app\` — Application orchestrator

Single entrypoint combining DI, HTTP server, dispatching, and scheduling.

\`\`\`go
app := app.New()
app.Provide("PingService", ping.NewPingService())
app.RegisterHTTP(&ping.PingEndpoint{})
app.RegisterAction("file.save", fileSaveHandler)
app.Schedule("cleanup", "0 3 * * *", cleanupHandler)
app.Use(srv.LoggingMiddleware)
app.Listen(":8080")
\`\`\`

- \`Provide(name, instance)\` — register DI dependency
- \`RegisterHTTP(h Handler)\` — register struct-tagged HTTP endpoint
- \`RegisterAction(name, handler)\` — register named dispatch handler
- \`Schedule(name, cron, handler)\` — register cron job
- \`Use(mw)\` — add HTTP middleware
- \`Build()\` → \`(*di.Container, error)\` — construct container + register handlers
- \`Listen(addr)\` — start server + scheduler + hosting, blocks

#### \`pkg/srv\` — Minimal API server

Routing, middleware, model binding, auth, validation, rate limiting. Radix tree O(depth) lookup with route constraints.

\`\`\`go
server := srv.New()
server.Use(srv.LoggingMiddleware)
server.RegisterHandler(&PingEndpoint{}, container)
server.Listen(":8080")
\`\`\`

Handler struct pattern:

\`\`\`go
type PingEndpoint struct {
    Meta  srv.Pattern \`method:"GET" path:"/api/ping"\`
    Times int         \`query:"times" default:"1"\`
}

func (e *PingEndpoint) Handle(ctx context.Context) (any, error) {
    return map[string]any{"pong": true}, nil
}
\`\`\`

Route constraints: \`{id:int}\`, \`{slug:alpha}\`, \`{name:regex(...)}\`, catch-all \`{*filepath}\`.

Built-in middleware: auth (\`srv.AuthMiddleware\`), validation (\`srv.ValidationMiddleware\`), rate limiting (\`srv.RateLimitMiddleware\`).

#### \`pkg/bind\` — Request binding

Populates struct fields from path params, query, headers, JSON body.

\`\`\`go
b := bind.New().
    FromPath(pathFunc).
    FromQuery(r).
    FromHeader(r)
b.Bind(&target)
b.BindJSON(&target, body)
\`\`\`

Tags: \`path:"id"\`, \`query:"times"\`, \`header:"Authorization"\`, \`default:"1"\`, \`body:"json"\`.

#### \`pkg/dispatcher\` — Named action dispatch

Synchronous named dispatch for GUI/TUI/CLI applications.

\`\`\`go
d := dispatcher.New()
d.Register("file.save", func(ctx context.Context, payload ...any) (any, error) {
    return nil, saveFile(payload[0].(string))
})
result, err := d.Dispatch(ctx, "file.save", "doc.txt")
\`\`\`

#### \`pkg/openapi\` — OpenAPI 3.0.3 generation

Generates OpenAPI docs from struct-tagged handlers.

\`\`\`go
doc, err := openapi.Build("My API", "1.0.0", &PingEndpoint{}, &UserEndpoint{})
\`\`\`

Handlers can implement \`MetaProvider\` interface for custom summaries, descriptions, parameters.

#### \`pkg/di\` — Dependency injection

Typed DI with Singleton/Scoped/Transient lifetimes, cycle detection, \`io.Closer\` tracking.

\`\`\`go
b := di.NewBuilder()
di.Register[Database](b, func() Database { return newDB() }, di.Singleton)
di.RegisterInstance[Config](b, cfg)
container, err := b.Build()   // returns (*Container, error) since v1.0.0

// Named resolution
b.Provide("db", dbInstance)
container.Inject(&handler)  // auto-populates fields with \`inject:"db"\` tag

// Typed resolution
db := di.ResolveType[Database](container)    // panics if not found
db, err := di.TryResolveType[Database](container)  // returns error
\`\`\`

Breaking change from pre-v1.0.0: \`Build()\` now returns \`(*Container, error)\`.

#### \`pkg/configuration\` — Multi-source configuration

.NET \`IConfiguration\`-style multi-source config with priority merging.

\`\`\`go
cfg := configuration.NewBuilder().
    AddEnv("APP_").
    AddJSONFile("config.json").
    Build()
val, ok := cfg.GetString("db:host")
\`\`\`

Providers: \`EnvProvider\` (env vars with prefix), \`FileProvider\` (JSON). Custom providers implement \`Provider\` interface.

Bind to struct via \`conf\` tags:

\`\`\`go
type Config struct {
    Port int    \`conf:"env:PORT,flag:--port,default:8080"\`
    DSN  string \`conf:"env:DATABASE_URL,flag:--dsn,required:true"\`
}
cfg.Bind(&configStruct)
\`\`\`

#### \`pkg/events\` — Type-safe event bus

Bounded channel with overflow strategies, async dispatch, middleware, wildcard subscriptions.

\`\`\`go
bus := events.New(events.WithStrategy(events.BestEffort))
events.Subscribe(bus, func(ctx context.Context, e UserCreated) error {
    return sendWelcomeEmail(e)
}, events.PriorityHigh)
events.Emit(ctx, bus, UserCreated{ID: "123"})
events.EmitAsync(ctx, bus, UserCreated{ID: "123"})
\`\`\`

Overflow strategies: \`OverflowBlock\` (default), \`OverflowDropOldest\`, \`OverflowFail\`.

**Important**: API uses \`events.Emit[T]\` and \`events.Subscribe[T]\` — NOT \`bus.Publish\`/\`bus.Subscribe\`.

#### \`pkg/auth\` — Token signing with key rotation

HMAC-SHA256, RSA-PKCS1v15, ECDSA P-256, Ed25519. Multi-key rotation via \`TokenService\`.

\`\`\`go
token, err := auth.SignToken(auth.Payload{Sub: "user", Exp: time.Now().Add(time.Hour).Unix()}, secret)
payload, err := auth.VerifyToken(token, secret)

// Multi-key service
svc := auth.NewService(
    auth.Key{ID: "1", Secret: secret, Algorithm: auth.AlgHMACSHA256},
)
signed, err := svc.Sign(claims)
claims, err := svc.Verify(signed.Token)
\`\`\`

Errors: \`ErrInvalidToken\`, \`ErrInvalidSignature\`, \`ErrExpiredToken\`, \`ErrUnknownKeyID\`.

#### \`pkg/guard\` — Declarative ABAC

Attribute-Based Access Control via struct tags. Two-pass resolution: dynamic roles from field comparison, then authorization check.

\`\`\`go
type Document struct {
    OwnerID string \`guard:"role:owner"\`
    Data    string \`guard:"read:owner,admin; write:owner; delete:admin"\`
}
err := guard.Can(user, document, "write")
\`\`\`

#### \`pkg/relay\` — Background job processing

Pub/sub with context propagation. \`MemoryBroker\` by default (zero infra).

\`\`\`go
relay := relay.New(relay.WithBroker(broker.NewMemoryBroker()))
relay.Register("send-email", func(ctx context.Context, p EmailPayload) error {
    return mailer.Send(p)
})
relay.Enqueue(ctx, "send-email", EmailPayload{To: "user@example.com"})
relay.Start(ctx)
\`\`\`

#### \`pkg/saga\` — Saga / compensation pattern

LIFO rollback, panic-safe, pluggable \`SagaStore\`, dead-letter queue.

\`\`\`go
wf := saga.New()
wf.Add("Charge Card",
    func(ctx context.Context) error { return chargeCard(ctx) },
    func(ctx context.Context) error { return refundCard(ctx) },
)
wf.AddGroup(saga.Group{
    {Name: "Send Email", Do: sendEmail, Compensate: noOp},
    {Name: "Send SMS", Do: sendSMS, Compensate: noOp},
})
result, err := wf.Run(ctx)
\`\`\`

Stores: \`MemoryStore\`, \`FileStore\`. State includes \`IdempotencyKey\`, \`RetryCount\`, \`MaxRetries\`, \`CreatedAt\`, \`UpdatedAt\`.

#### \`pkg/fsm\` — Declarative finite state machine

State topology via \`fsm\` struct tags. Guard/exit/entry hooks, timeout auto-transitions, Mermaid/Graphviz export.

\`\`\`go
type Order struct {
    Status string \`fsm:"initial:draft; draft->paid; *->cancelled"\`
}
func (o *Order) CanPaid() error { /* guard */ }
func (o *Order) OnEnterPaid()   { /* side effect */ }
machine, _ := fsm.New(&Order{})
machine.Transition("paid")
\`\`\`

Timeout transitions: \`draft->paid:30s\` auto-advances after 30s if still in source state.

#### \`pkg/caching\` — Generic cache with TTL

\`\`\`go
cache := caching.NewInMemory[string](
    caching.WithTTL[string](5*time.Minute),
    caching.WithMaxEntries[string](1000),
)
cache.Set(ctx, "key", "value", 0)
val, ok, err := cache.Get(ctx, "key")

// Distributed bridge
bridge := caching.NewDistributedBridge[User](redisBackend)
bridge.Set(ctx, "user:1", user, time.Minute)
\`\`\`

\`DistributedCache\` interface for Redis/Memcached backends. \`DistributedBridge[T]\` adapts to typed \`Cache[T]\`.

#### \`pkg/scheduler\` — Cron-based background jobs

\`\`\`go
sched := scheduler.New(
    scheduler.WithLogger(logFn),
    scheduler.WithMetrics(metricsFn),
    scheduler.WithStore("/var/data/scheduler"),
)
sched.Register(scheduler.Job{Name: "cleanup", Cron: "0 3 * * *", Handler: cleanup})
sched.Start(ctx)
\`\`\`

Persistent state via \`JobStore\`, fire-and-forget and delayed execution.

#### \`pkg/logger\` — Structured logging with sinks

JSON lines by default. Pluggable sinks, derived loggers, async mode.

\`\`\`go
lg := logger.New(logger.WithLevel(logger.DebugLevel))
reqLogger := lg.With(logger.Field{Key: "request_id", Value: "abc"})
reqLogger.Info("handling request", logger.Field{Key: "method", Value: "GET"})
\`\`\`

Sinks: \`ConsoleSink\` (default), \`CLEFSink\` (Serilog CLEF format), \`RotatingFileSink\`, \`PrometheusSink\`, \`TelegramSink\`.

CLEF output: \`@t\`, \`@l\` (omitted for Info), \`@m\`, flat fields at root.

#### \`pkg/metrics\` — Counter, Gauge, Histogram, Timer

\`\`\`go
counter := metrics.NewCounter()
counter.Inc()
counter.Add(4)

gauge := metrics.NewGauge()
histogram := metrics.NewHistogram(0, 10, 25, 50, 100, 250, 500, 1000)
timer := metrics.NewTimer()
timing := timer.Start()
// ... do work
timing.Stop()
\`\`\`

Interfaces: \`Counter\`, \`Gauge\`, \`Histogram\`, \`Timer\`. Plug in Prometheus/OpenTelemetry adapters.

#### \`pkg/httpx\` — HTTP client middleware

Composable \`http.RoundTripper\` pipeline with retry and circuit breaker.

\`\`\`go
cb := resiliency.NewCircuitBreaker(resiliency.WithThreshold(5))
client := httpx.New(nil, httpx.Header("User-Agent", "app/1.0"))
client.WithRetry(resiliency.WithAttempts(5))
client.WithBreaker(cb)
resp, err := client.Do(req)
\`\`\`

#### \`pkg/resiliency\` — Retry, circuit breaker, rate limiter, bulkhead

\`\`\`go
err := resiliency.Retry(ctx, fn,
    resiliency.WithAttempts(5),
    resiliency.WithInitialDelay(100*time.Millisecond),
    resiliency.WithMaxDelay(2*time.Second),
    resiliency.WithFactor(2.0))

cb := resiliency.NewCircuitBreaker(resiliency.WithThreshold(5))
err = cb.Execute(fn)
\`\`\`

Rate limiter (token bucket), bulkhead (concurrency limit), jitter backoff.

#### \`pkg/secrets\` — Secret store abstraction

Memory, Env, Cipher, Prefix, Fallback stores behind \`Store\` interface.

\`\`\`go
store := secrets.NewMemoryStore()
store.Set("db-password", []byte("secret"))
v, err := store.Get("db-password")

env := secrets.NewEnvStore()       // read-only
cipher, _ := secrets.NewCipherStore(env, key)  // AES-GCM at rest
prefixed := secrets.NewPrefixStore(store, "app:")
fallback := secrets.NewFallbackStore(primary, backup)
\`\`\`

#### \`pkg/plugin\` — Plugin registry + lifecycle + sandbox

\`\`\`go
registry := plugin.NewRegistry()
registry.Register(myPlugin{})
registry.StartAll()   // insertion order
registry.StopAll()    // reverse insertion order

sandbox := plugin.NewExecSandbox("/path/to/binary", "--flag")
\`\`\`

Router integration: \`plugin.RegisterRouteProviders(registry)\`. Exec sandbox via JSON-over-stdio. Shared-object loading.

#### \`pkg/worker\` — Fixed-size goroutine pool

\`\`\`go
pool := worker.NewPool(4)
defer pool.Shutdown()
pool.Submit(func(ctx context.Context) error { return doWork(ctx) })
\`\`\`

Unbuffered task channel (natural backpressure). Graceful shutdown via \`sync.Once\`. Context cancellation propagates to running tasks.

#### \`pkg/validation\` — Struct tag validation

\`\`\`go
v := validation.New()
errs := v.Validate(&req)  // validation.Errors
v.Register("custom", myRule)
\`\`\`

Built-in rules: \`required\`, \`email\`, \`min\`, \`max\`, \`len\`, \`minlen\`, \`maxlen\`, \`oneof\`. Type cache for O(1) repeat validation.

#### \`pkg/serializer\` — JSON serialization policy

\`\`\`go
p := serializer.New(
    serializer.WithNaming(serializer.SnakeCase),
    serializer.WithIgnoreNil(),
    serializer.WithCustomType(timeType, timeConverterFactory),
)
data, _ := p.Marshal(myStruct)
\`\`\`

Naming strategies: \`PascalCase\`, \`CamelCase\`, \`SnakeCase\`. Custom type converters via \`ConverterFactory\`.

#### \`pkg/telemetry\` — Tracer/Span/Meter/Counter/Histogram/Gauge

\`\`\`go
provider := telemetry.NewProvider(
    telemetry.WithTracer(myTracer),
    telemetry.WithMeter(myMeter),
)
span, ctx := provider.Tracer.Start(ctx, "operation")
span.SetAttributes(telemetry.Attribute{Key: "key", Value: "val"})
span.End()
\`\`\`

Exporters: \`NewOTLPExporter\` (batched HTTP/JSON), \`NewPrometheusExporter\` (text format). W3C \`traceparent\` propagation via \`TelemetryMiddleware.WrapHTTP\`.

#### \`pkg/health\` — Health check registry

\`\`\`go
reg := health.NewRegistry()
reg.Register("db", &DBChecker{})
reports := reg.CheckAll(ctx)
\`\`\`

Statuses: \`StatusHealthy\`, \`StatusDegraded\`, \`StatusUnhealthy\`.

#### \`pkg/pipeline\` — Generic middleware pipeline

\`\`\`go
p := pipeline.New[Request, Response]()
p.Use(authMiddleware)
p.Use(loggingMiddleware)
p.Then(finalHandler)
result, err := p.Process(ctx, input)
\`\`\`

#### \`pkg/testutil\` — Test utilities

\`\`\`go
host := testutil.NewTestHost(func(b *di.Builder, app *srv.Server) {
    di.RegisterInstance[Foo](b, foo)
    app.RegisterHandler(&MyEndpoint{}, nil)
})
defer host.Close()
resp := host.Get("/api/test")
\`\`\`

\`TestHost\`: DI container + \`httptest.Server\`. \`TestResponse\`: status, body, headers. \`Resolve[T]\` for typed DI.

#### \`pkg/errutil\` — Error handling with style

\`Auto()\` recovers from panics with ANSI colored stack traces. \`AutoHTTP\` middleware for HTTP handlers.

\`\`\`go
defer errutil.Auto()  // put at top of main()

// Rich errors
err = errutil.Wrap(err, "context")
err = errutil.WithCode(err, "NOT_FOUND")
errutil.Print(err)   // prints chain with stack
\`\`\`

#### \`pkg/contracts\` — Zero-cost interface markers

\`\`\`go
type MyService struct {
    contracts.Implements[IService]
}
contracts.MustVerify(&MyService{})
\`\`\`

#### \`pkg/lock\` — Lock interface + in-memory locker

\`\`\`go
type Locker interface {
    Acquire(ctx context.Context, key string, ttl time.Duration) error
    TryLock(ctx context.Context, key string, ttl time.Duration) (bool, error)
    Release(ctx context.Context, key string) error
}

memLock := lock.NewInMemoryLocker()
\`\`\`

\`Scope\` for scoped locks, \`ProvideLazy\` for DI-integrated lock providers.

#### \`pkg/options\` — Functional options pattern

\`\`\`go
type Option[T any] func(*T)
opts := options.Merge(opt1, opt2)  // combine option sets
\`\`\`

#### \`pkg/hooks\` — Lifecycle hook discovery

Auto-discovers \`OnEnter*\` / \`OnExit*\` methods via reflection. \`Run\` for parallel hook execution.

#### \`pkg/tags\` — Generic struct tag parser (cached)

\`\`\`go
p := tags.NewParser("conf",
    tags.WithPairDelimiter(";"),
    tags.WithKVSeparator(":"),
    tags.WithValueDelimiter(","),
    tags.WithIncludeUntagged())
meta := p.ParseStruct(myStruct)
kv := p.Parse(tagString)
\`\`\`

**Replaces \`go-struct-flags/v2\`** for new code.

#### \`pkg/safemap\` — Thread-safe map + sharded map with TTL

\`\`\`go
m := safemap.New[string, User]()
m.Set("id", user)
v, ok := m.Get("id")
m.Compute("id", func(v User, exists bool) User { return updated })

sm := safemap.NewSharded[string, User](64)
sm.SetTTL("id", user, 5*time.Minute)
\`\`\`

#### \`pkg/collections\` — Set, OrderedSet, Queue, MultiMap, BiMap

\`\`\`go
s := collections.NewSet[int](1, 2, 3)
os := collections.NewOrderedSet[string]("a", "b")
q := collections.NewQueue[int]()
mm := collections.NewMultiMap[string, int]()
bm := collections.NewBiMap[string, int]()
\`\`\`

#### \`pkg/adapters\` — Pluggable adapter registry

\`\`\`go
reg := adapters.NewRegistry[MyInterface]()
reg.Register("redis", redisImpl)
reg.SetDefault("redis")
impl, ok := reg.Get("redis")
\`\`\`

#### \`pkg/result\` — Rust-style Result monad

\`\`\`go
r := result.Ok(user)
r = result.Err[User](err)
r.IsOk(); r.Unwrap(); r.UnwrapOr(fallback)
mapped := result.Map(r, func(u User) string { return u.Name })
\`\`\`

#### Other packages

| Package | Purpose |
|---|---|
| \`pkg/ring\` | Generic ring buffer + byte ring |
| \`pkg/cpio\` | CPIO newc pack/unpack |
| \`pkg/align\` | Power-of-2 integer alignment (Up, Down) |
| \`pkg/pointer\` | Field offset registry |
| \`pkg/reflectutil\` | String-to-typed-value binding, struct population |
| \`pkg/pooling\` | Generic object pool with finalizer and max size |
| \`pkg/tracing\` | Tracer/Span interface + noop implementation |

---

### go-slipstream

\`github.com/mirkobrombin/go-slipstream\`

High-performance embedded database combining a Bitcask-style Write-Ahead Log with ACID transactions, secondary indexing, and optional Raft consensus for cluster deployments. No external database required.

#### API

\`\`\`go
eng := engine.NewBitcask[User](walManager, codec, decoder)
eng.Put(ctx, "user:123", user)
eng.Get(ctx, "user:123")
eng.Delete(ctx, "user:123")

tx, _ := eng.Begin()
tx.Put(ctx, "a", valA)
tx.Put(ctx, "b", valB)
tx.Commit(ctx)

eng.AddIndex("byEmail", func(u User) string { return u.Email })
eng.GetByIndex(ctx, "byEmail", "alice@example.com").Limit(10).All()
\`\`\`

External deps: raft, zstd, otel.

---

### go-warp

\`github.com/mirkobrombin/go-warp/v1\`

Data orchestration and synchronization layer. Two-tier (L1 in-memory / L2 store) cache with configurable consistency modes, distributed invalidation, distributed locking, leases, watch bus, versioned cache, Prometheus metrics. Sidecar mode with RESP protocol.

#### Consistency modes

| Mode | Behaviour |
|---|---|
| \`ModeStrongLocal\` | Consistent on this node only |
| \`ModeEventualDistributed\` | Local writes, async invalidation (default) |
| \`ModeStrongDistributed\` | Writes wait for quorum |

Sync bus backends: InMemory, Mesh (P2P UDP), Redis Pub/Sub, NATS, Kafka.

External deps: redis, nats, kafka, otel.

---

### go-wormhole

\`github.com/fabricatorsltd/go-wormhole\`

Entity Framework-inspired ORM / Data Mapper for Go, built on go-foundation. Code-first migrations, type-safe queries via a pointer-tracking DSL (zero code generation), Unit of Work change tracker with partial UPDATE, lifecycle hooks, SQL + NoSQL providers.

Current line: v1.7.x.

#### Bootstrap

\`\`\`go
import (
    "database/sql"
    _ "github.com/glebarez/sqlite"

    "github.com/fabricatorsltd/go-wormhole/pkg/dsl"
    wormholesql "github.com/fabricatorsltd/go-wormhole/pkg/sql"
)

func init() {
    // Pre-compute field memory offsets — one-time cost at startup.
    dsl.Register(User{})
    dsl.Register(Order{})
}

func main() {
    db, _ := sql.Open("sqlite", "app.db")
    wormholesql.RegisterDefault(db)
}
\`\`\`

#### Query and mutate

\`\`\`go
import (
    wh "github.com/fabricatorsltd/go-wormhole/pkg/context"
    "github.com/fabricatorsltd/go-wormhole/pkg/dsl"
    "github.com/fabricatorsltd/go-wormhole/pkg/provider"
    "github.com/fabricatorsltd/go-wormhole/pkg/query"
)

ctx := wh.New(provider.Default())
defer ctx.Close()

// Fetch by PK — auto-tracked as Unchanged
var u User
ctx.Set(&u).Find(42)

// Mutate in plain Go
u.Age = 35

// Flush — emits UPDATE "users" SET "age" = ? WHERE "id" = ?
ctx.Save()

// Type-safe DSL via pointer tracking
var users []User
ctx.Set(&users).
    Where(dsl.Gt(&u, &u.Age, 18)).
    OrderBy("age", query.Desc).
    Limit(10).
    All()

// Insert + delete
ctx.Add(&User{Name: "Alice", Age: 30})
ctx.Remove(&u)
ctx.Save()
\`\`\`

#### Entity states

\`Unchanged\` (matches DB) → \`Modified\` (dirty, partial UPDATE) → \`Unchanged\` after \`Save\`.
\`Added\` → INSERT → \`Unchanged\`. \`Remove()\` → \`Deleted\` → DELETE → removed from tracker.

Dirty detection: snapshot taken at \`Attach\`/\`Add\`/\`Find\`, \`DetectChanges()\` diffs each field via \`reflect.DeepEqual\` on \`Save\`. Only changed columns hit the wire.

#### Tags

\`primary_key\`, \`auto_increment\`, \`column:user_name\`, \`type:varchar(255)\`, \`nullable\`, \`index:idx_email\`, \`default:'active'\`. Untagged fields default to snake_case (\`UserID\` → \`user_id\`).

#### Providers

PostgreSQL, SQLite, MySQL, MSSQL (via \`pkg/sql\`), MongoDB, go-slipstream (Bitcask), MemDoc (in-memory). Engine-specific naming auto-applied (PascalCase for MSSQL, snake_case elsewhere). Cross-engine sync handles identity/sequence translation (e.g. MSSQL → Postgres).

#### Resilience

Retry with backoff, circuit breaker, aggregated \`MultiError\` — exposed by the provider layer for transient driver failures.

#### Lifecycle hooks

Auto-discovered via reflection: \`BeforeSave()\`, \`AfterInsert()\`, \`BeforeDelete()\`, \`AfterUpdate()\`, etc.

#### CLI

Two ways to invoke. Build-tag mode reuses your project's binary:

\`\`\`bash
go run -tags wormhole_cli . migrations add CreateUser
go run -tags wormhole_cli . database update
go run -tags wormhole_cli . migrations list
go run -tags wormhole_cli . migrations script
\`\`\`

Or install the standalone binary:

\`\`\`bash
go install github.com/fabricatorsltd/go-wormhole/cmd/wormhole@latest
wormhole migrations add CreateUser
wormhole database update
wormhole dbcontext scaffold
\`\`\`

Configuration via \`WORMHOLE_DSN\` and \`WORMHOLE_DRIVER\` env vars (\`sqlite\`, \`postgres\`, \`mysql\`, \`sqlserver\`).

External deps: mongo-driver, go-slipstream, glebarez/sqlite. DI via \`go-foundation/pkg/di\`.

---

## Design principles

- All modules are \`CGO_ENABLED=0\` safe
- **go-foundation** is the only shared base; zero external dependencies
- \`pkg/events\` (in-process, ephemeral) + \`pkg/relay\` (persistent, retryable) form a two-tier async pipeline
- go-warp syncbus supports multi-node cache consistency without changing application code
- \`pkg/srv\` + \`pkg/dispatcher\` replace \`go-module-router/v2\` in v1.1.0
- \`pkg/saga\` is panic-safe: a panicking step triggers full rollback
- \`pkg/app\` orchestrates DI + HTTP + dispatch + scheduling in a single entrypoint
- \`pkg/hosting\` manages service lifecycle with health endpoints and graceful shutdown

## Ecosystem integration pattern

\`\`\`
User intent
    │
    ▼
pkg/app            — single entrypoint: DI, HTTP, dispatch, scheduling
    │
    ├── pkg/srv     — HTTP routing, binding, auth, validation, rate limit
    ├── pkg/dispatcher — named action dispatch (GUI/TUI/CLI)
    ├── pkg/saga    — wraps multi-step logic in compensatable workflows
    ├── pkg/events  — emits completed action for in-process side effects
    └── pkg/relay   — enqueues durable background jobs
            │
            └── MemoryBroker (dev / single-node) — zero infrastructure

go-wormhole   — data access layer (code-first ORM, Unit of Work)
    └── providers: SQL / MongoDB / go-slipstream / MemDoc

go-warp       — caching + distributed cache invalidation
    └── sits between app logic and primary storage

go-slipstream — embedded Bitcask+Raft database
    └── used by go-wormhole (Slipstream provider) and go-warp (as L2 store)
\`\`\`

---

## Module quick-reference

| Module | Import path | Purpose | External deps |
|---|---|---|---|
| **go-foundation** | \`github.com/mirkobrombin/go-foundation\` | Shared primitives + hosted services, routing, DI, config, events, auth, guard, relay, saga, FSM, caching, scheduler, logger, metrics, httpx, resiliency, secrets, plugin, worker, validation, serializer, telemetry, health, pipeline, testutil, errutil, contracts, openapi, bind, dispatcher, app, hosting, srv | None |
| **go-slipstream** | \`github.com/mirkobrombin/go-slipstream\` | Embedded Bitcask+Raft database | raft, zstd, otel |
| **go-warp/v1** | \`github.com/mirkobrombin/go-warp/v1\` | L1/L2 cache + distributed sync | redis, nats, kafka, otel |
| **go-wormhole** | \`github.com/fabricatorsltd/go-wormhole\` | EF-style ORM, pointer-tracking DSL, Unit of Work, code-first migrations, lifecycle hooks, retry/circuit breaker, MSSQL/Postgres cross-engine sync | mongo-driver, go-slipstream, glebarez/sqlite |`;
