#!/usr/bin/env node
/**
 * Reads ../go-tools-index.md and generates data.ts with the content
 * embedded as a TypeScript string constant.
 *
 * Runs automatically via `postinstall`, or manually with `npm run update-index`.
 */
import { readFileSync, writeFileSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const indexPath = join(__dirname, "..", "go-tools-index.md");
const outputPath = join(__dirname, "data.ts");

let content;
try {
  content = readFileSync(indexPath, "utf-8");
} catch {
  console.error(`[update-index] ERROR: Could not read ${indexPath}`);
  console.error("  Make sure go-tools-index.md exists in the parent directory.");
  process.exit(1);
}

// Escape backticks and template literal placeholders for embedding
const escaped = content
  .replace(/\\/g, "\\\\")
  .replace(/`/g, "\\`")
  .replace(/\$\{/g, "\\${");

const output =
  `// AUTO-GENERATED by update-index.mjs — do not edit manually.\n` +
  `// Run \`npm run update-index\` (or \`npm install\`) to regenerate from ../go-tools-index.md.\n` +
  `// Last generated: ${new Date().toISOString()}\n` +
  `export const INDEX_CONTENT = \`${escaped}\`;\n`;

writeFileSync(outputPath, output, "utf-8");
console.log(
  `[update-index] Written data.ts (${content.length.toLocaleString()} chars from go-tools-index.md)`
);
