#!/usr/bin/env node
/**
 * Reads go-tools-index.md (co-located with package.json) and generates data.ts
 * with the content embedded as a TypeScript string constant.
 *
 * Runs automatically via `postinstall`, or manually with `npm run update-index`.
 * Non-fatal: exits 0 with a warning if the index file is not found (CI-safe).
 */
import { readFileSync, writeFileSync, existsSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));

// Primary: inside go-tools-mcp/. Fallback: monorepo root (dev convenience).
const candidates = [
  join(__dirname, "go-tools-index.md"),
  join(__dirname, "..", "go-tools-index.md"),
];

const indexPath = candidates.find(existsSync);

if (!indexPath) {
  console.warn("[update-index] WARNING: go-tools-index.md not found. Tried:");
  for (const p of candidates) console.warn(`  - ${p}`);
  console.warn(
    "  data.ts was not updated. Commit a pre-generated data.ts, or copy\n" +
    "  go-tools-index.md next to package.json before running npm install."
  );
  process.exit(0);  // non-fatal — Cloudflare build continues with committed data.ts
}

let content;
try {
  content = readFileSync(indexPath, "utf-8");
} catch (err) {
  console.error(`[update-index] ERROR: Could not read ${indexPath}: ${err.message}`);
  process.exit(0);  // non-fatal
}

// Escape backticks and template literal placeholders for embedding
const escaped = content
  .replace(/\\/g, "\\\\")
  .replace(/`/g, "\\`")
  .replace(/\$\{/g, "\\${");

const output =
  `// AUTO-GENERATED by update-index.mjs — do not edit manually.\n` +
  `// Run \`npm run update-index\` (or \`npm install\`) to regenerate from go-tools-index.md.\n` +
  `// Last generated: ${new Date().toISOString()}\n` +
  `export const INDEX_CONTENT = \`${escaped}\`;\n`;

const outputPath = join(__dirname, "data.ts");
writeFileSync(outputPath, output, "utf-8");
console.log(
  `[update-index] Written data.ts (${content.length.toLocaleString()} chars from ${indexPath})`
);

