#!/usr/bin/env node
/**
 * Reads ../go-tools-index.md and generates src/data/index.ts with the content
 * embedded as a TypeScript string constant.
 *
 * Run automatically via `postinstall`, or manually with `npm run update-index`.
 */
import { readFileSync, writeFileSync, mkdirSync } from "fs";
import { join, dirname } from "path";
import { fileURLToPath } from "url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const indexPath = join(__dirname, "..", "..", "go-tools-index.md");
const outputPath = join(__dirname, "..", "src", "data", "index.ts");

let content;
try {
  content = readFileSync(indexPath, "utf-8");
} catch (err) {
  console.error(`[update-index] ERROR: Could not read ${indexPath}`);
  console.error(`  Make sure go-tools-index.md exists in the parent directory.`);
  process.exit(1);
}

// Escape for embedding in a template literal
const escaped = content
  .replace(/\\/g, "\\\\")
  .replace(/`/g, "\\`")
  .replace(/\$\{/g, "\\${");

const output = `// AUTO-GENERATED by scripts/update-index.mjs — do not edit manually.
// Run \`npm run update-index\` (or \`npm install\`) to regenerate from ../go-tools-index.md.
// Last generated: ${new Date().toISOString()}
export const INDEX_CONTENT = \`${escaped}\`;
`;

mkdirSync(dirname(outputPath), { recursive: true });
writeFileSync(outputPath, output, "utf-8");
console.log(
  `[update-index] Written src/data/index.ts (${content.length.toLocaleString()} chars from go-tools-index.md)`
);
